import './globals.css'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import { GlobalProvider } from './GlobalProvider'
import 'react-toastify/dist/ReactToastify.css';
const inter = Poppins({
  weight: ['400','500','600', '700','800'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Pickleball Adventures',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalProvider >
      <body className={inter.className}>{children}</body>
      </GlobalProvider>
    </html>
  )
}
